### PR TITLE
Add HERMES_PUSH_TOKEN

### PR DESCRIPTION
**Pull request by SKernchen**
See #201 for Information.

### CODE REVIEW

**Comment by daniel-mohr** [comment]
Since the necessary `HERMES_PUSH_TOKEN` is really powerful, I would also suggest to warn/inform the user, e. g.:

```md
The `HERMES_PUSH_TOKEN` is really powerful! Therefore you should ensure that only people with at least
the same rights on your project could access this CI variable.
This means you should at least select the flag `Mask variable`.
If possible you should also select the flag `Protect variable` and define all branches `hermes/*` as
protected branch.
```

Further I would suggest a similar warning regarding the `ZENODO_TOKEN`, e. g.:

```md
The `ZENODO_TOKEN` is a personal access token to your invendio/zenodo account.
Therefore you should ensure that you do not share it with other people.
This means you have to be the only `Developer`, `Maintainer` and `Owner` in your project.
Further you should at least select the flag `Mask variable`.
If possible you should also select the flag `Protect variable` and define all branches `hermes/*` as
protected branch.
```

**Comment by SKernchen** [comment]
> Since the necessary `HERMES_PUSH_TOKEN` is really powerful, I would also suggest to warn/inform the user, e. g.:
> 
> ```
> The `HERMES_PUSH_TOKEN` is really powerful! Therefore you should ensure that only people with at least
> the same rights on your project could access this CI variable.
> This means you should at least select the flag `Mask variable`.
> If possible you should also select the flag `Protect variable` and define all branches `hermes/*` as
> protected branch.
> ```
> 
> Further I would suggest a similar warning regarding the `ZENODO_TOKEN`, e. g.:
> 
> ```
> The `ZENODO_TOKEN` is a personal access token to your invendio/zenodo account.
> Therefore you should ensure that you do not share it with other people.
> This means you have to be the only `Developer`, `Maintainer` and `Owner` in your project.
> Further you should at least select the flag `Mask variable`.
> If possible you should also select the flag `Protect variable` and define all branches `hermes/*` as
> protected branch.
> ```

Thank you for contributing @daniel-mohr , i will adapt your remarks 😃.

**Comment by daniel-mohr** [comment]
@SKernchen I think you missed my inline comment / review comment, isn' it?

cf.:
> `write_repository` (write access to the repository) is enough
> `api` (write access to the project)

**Comment by SKernchen** [comment]
@daniel-mohr Oh I'm sorry but what exactly do you mean?
For the Hermes Push Token write acces is needed.
In the tutorial i propose to use the `write_repository` scope which is the more limited than the api scope.
There is also the documentation link for creating personal access token where one individual can see which fits best.

**Comment by daniel-mohr** [comment]
@SKernchen I repeat here my complete [inliine comment / review comment](https://github.com/hermes-hmc/workflow/pull/223/files):

Maybe it would help to use the gitlab vocabulary:

* `developer` -> `Developer`

Further I do not think `write_repository` (write access to the repository) is enough. At the actual workflow -- as I used it a few months ago -- creates branches. In this way the necessary scope would be `api` (write access to the project).

In #203 I proposed some other possible workflows. Some of these would allow to use `write_repository` only.

**Comment by daniel-mohr** [comment]
So, the Hermes Push Token needs write access to the project. It is not enough to have write access to the repository!

**Comment by led02** [comment]
> So, the Hermes Push Token needs write access to the project. It is not enough to have write access to the repository!

Well, we're just in process of integrating this into a GitLab training and `write_repository` is indeed enough

**Comment by daniel-mohr** [comment]
@led02 But the workflow creates still branches, isn't like this anymore?

**Comment by led02** [comment]
> @led02 But the workflow creates still branches, isn't like this anymore?

Yes, it does create branches and a merge request. But it does so by using Git push magic:
```
git push origin "$MR_SOURCE_BRANCH"
    -o merge_request.create
    -o merge_request.target="$MR_TARGET_BRANCH"
    -o merge_request.title="$MR_TITLE"
    -o merge_request.description="$MR_DESCRIPTION"
    -o merge_request.remove_source_branch
```

This does not require API access.

**Comment by daniel-mohr** [comment]
@SKernchen Thanks for solving my issue!

**Pull request merged**
